### ISSUE TITLE
readme is wrong

### ISSUE THREAD

**Issue by Zamiell** [JPeer264/node-is-git-dirty#22]
Hello, and thanks for the library.

The main export is called `isGitClean`, not `isGitDirty`, so the instructions should probably be inverted. (?)

Additionally, can you add information on TypeScript usage to the readme?

**Comment by JPeer264** [comment]
Thanks a lot for pointing that out! I am not sure if I am understanding that correctly, but with TypeScript the types should be added automatically when you import the module. Just in case I updated the README into `import`s
